[workspace]
members = [
    "oracle",
    "contracts",
    "utils"
]



[package]
name = "drng-protocol"
version = "0.1.0"
authors = ["Menna <emanuele.cryptdev@gmail.com>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/0xMenna01/drng-protocol"
description = "A decentralised random number generator based on the VDF (Verifiable Delay Function)"
keywords = ["blockchain", "smart-contracts", "ink", "wasm", "random", "crypto", "vdf", "p2p"]
include = ["Cargo.toml", "src/**/*.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "oracle"
path = "oracle/src/main.rs"

[dependencies]
libp2p = "0.51.3"


anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive", "env"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
scale = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
which = "4.4.0"
colored = "2.0.0"
serde = { version = "1.0.163", default-features = false, features = ["derive"] }
serde_json = "1.0.96"
rust_decimal = "1.29"


# dependencies for extrinsics (deploying and calling a contract)
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
sp-core = "20.0.0"
sp-runtime = "23.0.0"
sp-weights = "19.0.0"
pallet-contracts-primitives = "23.0.0"
scale-info = "2.7.0"
subxt = "0.28.0"
hex = "0.4.3"
jsonrpsee = { version = "0.18.2", features = ["ws-client"] }
